name: Build

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build and publish image
      env:
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
      run: ./build.sh
